### ISSUE TITLE
Help me what i did wrong

### ISSUE THREAD

**Issue by kmkmahesh** [jacob-l/WopiHost#1]
while i changing the discovery.xml with mine i am getting the error of < and > so i made find and replace in xml with escaped characters of &amp; &gt; and &lt;  where they are required .

I can edit files perfectly using sharepoint document library but i dont need sharepoint for my requirement. 

i am getting the below errors and i cant understand what to do now expecting help from you.

Error while opening Powerpoint file
![image](https://cloud.githubusercontent.com/assets/11221507/6405986/7505ccdc-be50-11e4-9894-4e6f4c2ab9fe.png)

Error while opening excel file
![image](https://cloud.githubusercontent.com/assets/11221507/6405998/a7a80f24-be50-11e4-9308-5da6eb896f26.png)

Error while opening Word file
![image](https://cloud.githubusercontent.com/assets/11221507/6406004/c48c9e48-be50-11e4-9456-0e2531e43022.png)

**Comment by jacob-l** [comment]
Could you please attach your discovery.xml ?

**Comment by kmkmahesh** [comment]
thnx for fast reply but i think you wont available for weekend and me too out from city where i dont have internet to check everything.

At first i copied and pasted the .xml from browser and done the replacing with & where they are needed after that i saved the .xml from browser and rechecked with the newone also but it gives the same error.

i cant come to any conclusion that did i miss any thing or i just replacing the xml works fines.

This is the discovery.xml of mine

http://pastebin.com/xArjYtAA

I have 4 virtual machines in total 
 3 of them are Windows server 2012 R2
1. Domain Controller
2. SharePoint and MSSQL 
3. Office Web Apps Server

and the other is windows 8.1 Enterprise for other testing operations i installed iis in windows 8.1 and tested the above from 8.1 itself.

If possible please give me a good example how to create access token for a file. Is it created by program as static way or created by WOPI server or randomly created using file permission of the folder.  i really confused understanding this thing really it is very helpful to me if i got this point.

I am not programmer bro i just use all the code to test everything what i need.

**Comment by jacob-l** [comment]
I don't see any problem with your discovery.xml
Looks like Office Web Apps can not load file from Wopi Host.

Do you run wopi host from this repository or something else?

About tokens. In my project I create token for each file and store it in DB.

**Comment by kmkmahesh** [comment]
Thnx for reply bro

As I said I used 4 virtual machines earlier to test office web apps server  to edit office documents.

Windows server 2012 R2 machines 

Domain controller
Sharepoint and mssql server
Office web apps server

Client machine with windows 8.1 enterprise
It is perfectly working with share point but I installed iis in windows 8.1 machine and copied your app on it 

It is creating access token also. But I am getting those errors

Help me for this

**Comment by jacob-l** [comment]
By your screenshots and discovery.xml I suggest that windows 8.1 has address - lwa-pc.linkwebapps.tk (Right?)

Try to open in browser  http://lwa-pc.linkwebapps.tk/wopi/files/test.docx . What do you see?

P.S. Did you enable HTTP for OWA? Did you try to read logs of Office Web Apps server?

**Comment by kmkmahesh** [comment]
Yes windows 8.1 has name lwa-pc.linkwebapps.tk

Server Error in '/wopi' Application.

The resource cannot be found.

Description: HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable.  Please review the following URL and make sure that it is spelled correctly. 

Requested URL: /wopi/files/test.docx

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.34212

i already enabled it after creating the Office Web Apps Server Farm.

**Comment by jacob-l** [comment]
What is path of application in IIS? Is it hosted on this url lwa-pc.linkwebapps.tk? Or maybe there is some addition path to this url?

**Comment by jacob-l** [comment]
Try also please http://lwa-pc.linkwebapps.tk/wopi/wopi/files/test.docx

**Comment by kmkmahesh** [comment]
yes it is hosted on lwa-pc.linkwebapps.tk/wopi.  if you want i can give you remote of my machine, i tried both but not succeded

i am getting the below error 

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Message>
No HTTP resource was found that matches the request URI 'http://lwa-pc.linkwebapps.tk/wopi/wopi/files/test.docx'.
</Message>
<MessageDetail>
No action was found on the controller 'Wopi' that matches the request.
</MessageDetail>
</Error>

**Comment by kmkmahesh** [comment]
tried both but not succeded

**Comment by jacob-l** [comment]
I don't think that remote is a good idea.

What is address of home page for this wopi host? Home page contains this header - "Press any link to view file:"

**Comment by kmkmahesh** [comment]
lwa-pc.linkwebapps.tk/wopi is the home page but my router not supporting port forwarding so it is impossible to check from outside

my iis 

![iis](https://cloud.githubusercontent.com/assets/11221507/6455867/128749e0-c180-11e4-88d2-c9e45844ec5a.JPG)

wopi home page
![wopi home](https://cloud.githubusercontent.com/assets/11221507/6455891/53d97a08-c180-11e4-82da-c410aa6982de.JPG)

i am not saying problem in your project i think i missed some thing where i cant find what i missed

is there any folder sharing permissions needed for me

**Comment by jacob-l** [comment]
I forget to add fake token to the link. What do you see?
http://lwa-pc.linkwebapps.tk/wopi/wopi/files/test.docx?access_token=62a8238e-aea1-4a58-a652-8896e2c91957

**Comment by kmkmahesh** [comment]
<FileInfoDto xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/WopiHost.Dto">
<BaseFileName>test.docx</BaseFileName>
<OwnerId>admin</OwnerId>
<ReadOnly>true</ReadOnly>
<SHA256>BlEHK/mcCGqzdURXrDyEflu7m57aXGITiHLfxqsM7A0=</SHA256>
<Size>12736</Size>
<Version>1</Version>
</FileInfoDto>

**Comment by jacob-l** [comment]
It means that wopi works good. Can you try to open this link from the PC where Office Web Apps installed?

**Comment by kmkmahesh** [comment]
ok wait for minute please

you mean the above link or wopi server link lwa-pc.linkwebapps.tk/wopi ???

**Comment by kmkmahesh** [comment]
web app is not loading from office web apps server maching

**Comment by jacob-l** [comment]
I did not catch your last message. Explain please(Or screenshot)

**Comment by kmkmahesh** [comment]
![not loading](https://cloud.githubusercontent.com/assets/11221507/6455992/e290c8a4-c181-11e4-96f0-1273a46d90b1.JPG)

**Comment by jacob-l** [comment]
I understood. It is a problem. I suppose that there is problem in configuration in your network. Server with wopi host must be accessible from office web apps server.

**Comment by kmkmahesh** [comment]
wait i will ping each first

**Comment by kmkmahesh** [comment]
![ping](https://cloud.githubusercontent.com/assets/11221507/6456014/359ab942-c182-11e4-929e-1451589984b7.JPG)

after testing this also i am getting the same error

**Comment by jacob-l** [comment]
Add line to your hosts file:
192.168.2.125 lwa-pc.linkwebapps.tk

How to configure hosts file
http://www.howtogeek.com/howto/27350/beginner-geek-how-to-edit-your-hosts-file/

OR
Try to work with Wopi Host on host machine via IP - open http://192.168.2.125/wopi and press any link

**Comment by kmkmahesh** [comment]
already tried the second one before pinging

**Comment by kmkmahesh** [comment]
my DNS from DC

![dc dns](https://cloud.githubusercontent.com/assets/11221507/6456091/44191e68-c183-11e4-8429-e94a4e5c7016.JPG)

**Comment by jacob-l** [comment]
Maybe some firewall rules blocks traffic to wopihost?

**Comment by kmkmahesh** [comment]
i will turn off firewall now wait please

**Comment by kmkmahesh** [comment]
yep firewall does everything i didn't noticed that bro

**Comment by kmkmahesh** [comment]
is this project wont help me on editing the office documents ???

i am just getting the viewer not edit option

**Comment by jacob-l** [comment]
You can edit Excel and PowerPoint documents via Office Web Apps, but it requires license from Microsoft and implementation editing in WopiHost project(But there are examples in Internet with editing)

Please, take into account, My WopiHost project is example and has not any access file protection.

**Comment by kmkmahesh** [comment]
i have working editing option from the sharepoint

**Comment by kmkmahesh** [comment]
i tried but i cant find any thing to edit office documents mainly word document without sharepoint

**Comment by jacob-l** [comment]
Editing word documents requires implementation of FSSHTTP protocol which is closed. As I know, nobody except of Microsoft implemented this protocol.

I think that for editing documents you can try another solution - https://www.onlyoffice.com/community-server.aspx . I did not try this, but read a lot.

**Comment by kmkmahesh** [comment]
thanx for help

**Comment by sag3ll0** [comment]
Приветствую, у меня возникла проблема аналогичная у предыдущего человека, вот только я запнулся на этапе что строка "http://<server>/wopi/wopi/files/test.docx?access_token=62a8238e-aea1-4a58-a652-8896e2c91957" выдает 
![image](https://cloud.githubusercontent.com/assets/18505406/17820926/cb164fa6-6657-11e6-8c02-2d89e1702f50.png)
Буду рад если сможете помочь

**Comment by sag3ll0** [comment]
настройки wopi
![image](https://cloud.githubusercontent.com/assets/18505406/17820963/f30147aa-6657-11e6-8940-a63e45b20064.png)
стоит на той же машине где и office online (кстати ставил microsoft office online 2016)
Ставил все по вашей статье на хабре.

**Comment by sag3ll0** [comment]
![image](https://cloud.githubusercontent.com/assets/18505406/17831497/0deefc2e-66f3-11e6-9a96-6a0e7dc349cc.png)
предыдущую проблему решил, теперь вот какая возникает, судя по гуглению надо установить флаг проверки [ValidateInput(false)] но где я не понимаю
