### ISSUE TITLE
Обнаружено потенциально опасное значение Request.Path, полученное от клиента (&).

### ISSUE THREAD

**Issue by sag3ll0** [jacob-l/WopiHost#2]
Здравствуйте при попытке доступа к файлу по адресу http://localhost:5524/wopi/files/test.docx&access_token=52d71e09-7846-4bab-8745-db029f956ee0 выдает следующую ошибку
![image](https://cloud.githubusercontent.com/assets/18505406/17831509/859c53ca-66f3-11e6-9206-ef23d47a38ec.png)

гугление дало что надо изменить где то параметр [ValidateInput(false)] или
 <configuration> <system.web> <pages validateRequest="false" /> </system.web> </configuration> в web.config, но после изменений у меня так же ничего не получается, возможно я не там это делаю, не могли бы вы мне помочь?

**Comment by jacob-l** [comment]
Здравствуйте!

URL c ошибкой. Должно быть http://localhost:5524/wopi/files/test.docx?access_token=52d71e09-7846-4bab-8745-db029f956ee0

Параметры к запросу начинаются после ?. Разделитель параметров — знак &

**Comment by sag3ll0** [comment]
Да вы правы, тут я действительно накосячил
